In [1]:
import numpy as np

pi = np.array([0.35,0.25,0.4])
S = ["Rainy", "Cloudy", "Sunny"]  # states
O = ["Read", "Play", "Shop"]  # observations space
P = np.array([[0.4, 0.2, 0.4], [0.2, 0.5, 0.3], [0.3, 0.6, 0.1]])
E = np.array([[0.8, 0.1, 0.1], [0.2, 0.5, 0.3],[0.4, 0.2, 0.4]])


Y = np.array([0,0,2,1,2])

v_prob = np.zeros([len(pi), len(Y)])  # size of viterbi matrix if (no of states and no of observations not observables)
v_path = np.zeros([len(pi), len(Y)])

for i in range(len(pi)):  # pi has all the states
    v_prob[i, 0] = pi[i] * E[i, Y[0]]  # Y[0] because this will give us the first observed observable.
    v_path[i,0] = -5

for j in range(1, len(Y)):  # len(Y)= length of observations=T
    for i in range(len(S)):  # len(s)= no of states=K
        maximum = -1
        alpha = -1
        for a in range(len(S)):
            
            temp = E[i, Y[j]] * P[a, i] * v_prob[a, j - 1]
            if temp > maximum:
                maximum = temp  # working as max
                alpha = a  # storing the last path in alpha. working as argmax. finding the index
        v_prob[i, j] = maximum  # maximum probability for an observation given a state (considering every path).
        v_path[i, j] = alpha

m, n = np.shape(v_prob)  # finding the shape of the viterbi probabilty matrix
index = 0
MAX = 0
for i in range(m):
    if MAX < v_prob[i, n - 1]:  # we are checking for the maximum probability in the last column of the viterby probability matrix.
        MAX = v_prob[i, n - 1]
        index = i

path = []
curobs = index  # which path that I came from
for node in range(n - 1, -1, -1):  # this is done for retracing the path
    path.append(int(curobs))
    curobs = v_path[int(curobs)][int(node)]

PATH = path[::-1]

print(v_prob[index,n-1])
print(v_prob)
print(v_path)
for i in PATH:
    print(S[i])
import numpy as np

pi = np.array([0.2, 0.3, 0.5])
S = ["normal","alternate","direct"]  # states
O = ["Up","Down"]  # observations space
P = np.array([[0.35, 0.45, 0.2], [0.28, 0.32, 0.4], [0.75, 0.1, 0.15]])
E = np.array([[0.1, 0.9], [0.6, 0.4],[0.7, 0.3]])


Y = np.array([0,1,1,1,0,0,0,1,0,1])

v_prob = np.zeros([len(pi), len(Y)])  # size of viterbi matrix if (no of states and no of observations not observables)
v_path = np.zeros([len(pi), len(Y)])

for i in range(len(pi)):  # pi has all the states
    v_prob[i, 0] = pi[i] * E[i, Y[0]]  # Y[0] because this will give us the first observed observable.

for j in range(1, len(Y)):  # len(Y)= length of observations=T
    for i in range(len(S)):  # len(s)= no of states=K
        maximum = -1
        alpha = -1
        for a in range(len(S)):
            
            temp = E[i, Y[j]] * P[a, i] * v_prob[a, j - 1]
            if temp > maximum:
                maximum = temp  # working as max
                alpha = a  # storing the last path in alpha. working as argmax. finding the index
        v_prob[i, j] = maximum  # maximum probaility for an observation given a state (considering every path).
        v_path[i, j] = alpha

m, n = np.shape(v_prob)  # finding the shape of the viterbi probabilty matrix
index = 0
MAX = 0
for i in range(m):
    if MAX < v_prob[i, n - 1]:  # we are checking for the maximum probaility in the last column of the viterby probalility matrix.
        MAX = v_prob[i, n - 1]
        index = i

path = []
curobs = index  # which path that I came from
for node in range(n - 1, -1, -1):  # this is done for retracing the path
    path.append(int(curobs))
    curobs = v_path[int(curobs)][int(node)]

PATH = path[::-1]


for i in PATH:
    print(S[i])

0.0006451200000000002
[[2.80000e-01 8.96000e-02 3.58400e-03 4.30080e-04 8.60160e-05]
 [5.00000e-02 1.92000e-02 8.06400e-03 4.30080e-03 6.45120e-04]
 [1.60000e-01 4.48000e-02 1.43360e-02 4.83840e-04 5.16096e-04]]
[[-5.  0.  0.  2.  1.]
 [-5.  2.  2.  2.  1.]
 [-5.  0.  0.  1.  1.]]
Rainy
Rainy
Sunny
Cloudy
Cloudy
direct
normal
normal
normal
alternate
alternate
direct
normal
direct
normal
