In [1]:
# 1 b

import numpy as np

def forward(P, E, S, O, Y):
    pi = [0.35, 0.25, 0.4]
    mat = np.zeros([len(pi), len(Y)])
    
    for i in range(len(pi)):
        mat[i][0] = pi[i] * E[i][Y[0]]
    
    for j in range(1, len(Y)):
        for i in range(len(S)):
            total = 0
            for a in range(len(S)):
                temp = E[i, Y[j]] * P[a, i] * mat[a, j-1]
                total += temp
            mat[i, j] = total
    print(mat)
    
    prob = 0
    for i in range(len(S)):
        prob = prob + mat[i, len(Y)-1]
    
    return prob

# Define model parameters
P = np.array([[0.4,0.2,0.4],
              [0.2,0.5,0.3],
              [0.3,0.6,0.1]])
E = np.array([[0.8,0.1,0.1],
              [0.2,0.5,0.3],
              [0.4,0.2,0.4]])
S = [0, 1, 2]  # rainy cloudy sunny
O = [0, 1, 2]     # reading playing shopping

Y1 = [0,0,2,1,2]
print("Probability for [read read shop play shop]:", forward(P, E, S, O, Y1))



[[0.28       0.136      0.007864   0.00163876 0.00044851]
 [0.05       0.0354     0.023766   0.0152167  0.00285261]
 [0.16       0.0572     0.028296   0.002621   0.00219305]]
Probability for [read read shop play shop]: 0.005494170600000001


In [16]:
#2 b

import numpy as np

def forward(P, E, S, O, Y):
    pi = [0.2,0.3,0.5]
    mat = np.zeros([len(pi), len(Y)])
    
    for i in range(len(pi)):
        mat[i][0] = pi[i] * E[i][Y[0]]
    
    for j in range(1, len(Y)):
        for i in range(len(S)):
            total = 0
            for a in range(len(S)):
                temp = E[i, Y[j]] * P[a, i] * mat[a, j-1]
                total += temp
            mat[i, j] = total
    
    prob = 0
    for i in range(len(S)):
        prob += mat[i, len(Y)-1]
    
    return prob

P = np.array([[0.35, 0.45, 0.2],
              [0.28, 0.32, 0.4],
              [0.75, 0.1, 0.15]])
E = np.array([[0.1, 0.9],
              [0.6, 0.4],
              [0.7, 0.3]])
S = [0, 1, 2]  # normal, alternate, direct
O = [0, 1]     # 0 for up and 1 for down

Y1 = [0, 0, 0, 0, 0, 0, 0, 0]
print("Probability for Y1:", forward(P, E, S, O, Y1))

Y2 = [1, 0, 1, 0, 1, 0, 1, 0]
print("Probability for Y2:", forward(P, E, S, O, Y2))

Y3 = [0, 1, 0, 1, 0, 1, 0, 1]
print("Probability for Y3:", forward(P, E, S, O, Y3))

Y4 = [0,0,1,0,1,1,1,0]
print("Probability for Y4:", forward(P, E, S, O, Y4))

Y5 = [1, 1, 1, 1, 1, 1, 1, 1]
print("Probability for Y5:", forward(P, E, S, O, Y5))

y = [0,1]
denominator = forward(P, E, S, O, y)


Probability for Y1: 0.0004479668654825981
Probability for Y2: 0.0030226812589211702
Probability for Y3: 0.006147664980957778
Probability for Y4: 0.004227104015319533
Probability for Y5: 0.00911509965898073


In [13]:
def calculating_probability(obs, g_states, pi, probability_matrix, emission_matrix):
    prob = np.zeros(len(obs))

    # print(g_states[0], obs[0])
    # print(emission_matrix[g_states[0], obs[0]])
    prob[0] = pi[obs[0]] * emission_matrix[g_states[0], obs[0]]

    
    for i in range(1, len(obs) ):
        prob[i ] = prob[i -1 ] * probability_matrix[g_states[i - 1] , g_states[i] ] * emission_matrix[g_states[i] , obs[i - 1]]

    return prob

states = ["rainy", "sunny", "cloudy" ]
observations = ["read", "shop", "play"]
pi = np.array([0.35, 0.25, 0.4])
probability_matrix = np.array([[0.4, 0.2, 0.4], [0.2, 0.5, 0.3], [0.3, 0.6, 0.1]])
emission_matrix = np.array([[0.8, 0.1, 0.1], [0.2, 0.5, 0.3], [0.4, 0.2, 0.4]])

observed = ["play", "read","play"]
stats = ["sunny", "sunny","cloudy"]
observed_index = [observations.index(i) for i in observed]
obs_st_index = [states.index(j) for j in stats]
numerator = calculating_probability(observed_index, obs_st_index, pi, probability_matrix, emission_matrix)

print(numerator[-1]/denominator)

0.005883955325524381


In [17]:
#2 b

import numpy as np

def forward(P, E, S, O, Y):
    pi = [0.2,0.3,0.5]
    mat = np.zeros([len(pi), len(Y)])
    
    for i in range(len(pi)):
        mat[i][0] = pi[i] * E[i][Y[0]]
    
    for j in range(1, len(Y)):
        for i in range(len(S)):
            total = 0
            for a in range(len(S)):
                temp = E[i, Y[j]] * P[a, i] * mat[a, j-1]
                total += temp
            mat[i, j] = total
    
    prob = 0
    for i in range(len(S)):
        prob += mat[i, len(Y)-1]
    
    return prob

P = np.array([[0.35, 0.45, 0.2],
              [0.28, 0.32, 0.4],
              [0.75, 0.1, 0.15]])
E = np.array([[0.5,0.5],
              [0.5,0.5],
              [0.5,0.5]])
S = [0, 1, 2]  # normal, alternate, direct
O = [0, 1]     # 0 for up and 1 for down

Y1 = [0, 0, 0, 0, 0, 0, 0, 0]
print("Probability for Y1:", forward(P, E, S, O, Y1))

Y2 = [1, 0, 1, 0, 1, 0, 1, 0]
print("Probability for Y2:", forward(P, E, S, O, Y2))

Y3 = [0, 1, 0, 1, 0, 1, 0, 1]
print("Probability for Y3:", forward(P, E, S, O, Y3))

Y4 = [0,0,1,0,1,1,1,0]
print("Probability for Y4:", forward(P, E, S, O, Y4))

Y5 = [1, 1, 1, 1, 1, 1, 1, 1]
print("Probability for Y5:", forward(P, E, S, O, Y5))

y = [0,1]
denominator = forward(P, E, S, O, y)


Probability for Y1: 0.00390625
Probability for Y2: 0.00390625
Probability for Y3: 0.00390625
Probability for Y4: 0.00390625
Probability for Y5: 0.00390625


In [21]:
#2 b

import numpy as np

def forward(P, E, S, O, Y):
    pi = [0.2,0.3,0.5]
    mat = np.zeros([len(pi), len(Y)])
    
    for i in range(len(pi)):
        mat[i][0] = pi[i] * E[i][Y[0]]
    
    for j in range(1, len(Y)):
        for i in range(len(S)):
            total = 0
            for a in range(len(S)):
                temp = E[i, Y[j]] * P[a, i] * mat[a, j-1]
                total += temp
            mat[i, j] = total
    
    prob = 0
    for i in range(len(S)):
        prob += mat[i, len(Y)-1]

    
    
    return prob

P = np.array([[0.35, 0.45, 0.2],
              [0.28, 0.32, 0.4],
              [0.75, 0.1, 0.15]])
S = [0, 1, 2]  # normal, alternate, direct
O = [0, 1]     # 0 for up and 1 for down

data_emission = 1/(len(O))

E = np.full((len(S), len(O)), data_emission )


Y1 = [0, 0, 0, 0, 0, 0, 0, 0]
print("Probability for Y1:", forward(P, E, S, O, Y1))

Y2 = [1, 0, 1, 0, 1, 0, 1, 0]
print("Probability for Y2:", forward(P, E, S, O, Y2))

Y3 = [0, 1, 0, 1, 0, 1, 0, 1]
print("Probability for Y3:", forward(P, E, S, O, Y3))

Y4 = [0,0,1,0,1,1,1,0]
print("Probability for Y4:", forward(P, E, S, O, Y4))

Y5 = [1, 1, 1, 1, 1, 1, 1, 1]
print("Probability for Y5:", forward(P, E, S, O, Y5))

y = [0,1]
denominator = forward(P, E, S, O, y)


Probability for Y1: 0.00390625
Probability for Y2: 0.00390625
Probability for Y3: 0.00390625
Probability for Y4: 0.00390625
Probability for Y5: 0.00390625


In [22]:
#2 b

import numpy as np

def forward(P, E, S, O, Y):
    pi = [0.2,0.3,0.5]
    mat = np.zeros([len(pi), len(Y)])
    
    for i in range(len(pi)):
        mat[i][0] = pi[i] * E[i][Y[0]]
    
    for j in range(1, len(Y)):
        for i in range(len(S)):
            total = 0
            for a in range(len(S)):
                temp = E[i, Y[j]] * P[a, i] * mat[a, j-1]
                total += temp
            mat[i, j] = total
    
    prob = 0
    for i in range(len(S)):
        prob += mat[i, len(Y)-1]
    
    return prob


S = [0, 1, 2]  # normal, alternate, direct
O = [0, 1]     # 0 for up and 1 for down
s_data = 1/len(S)
data_emission = 1/(len(O))
P=np.full((len(S),len(S)),s_data)
E = np.full((len(S), len(O)), data_emission )


Y1 = [0, 0, 0, 0, 0, 0, 0, 0]
print("Probability for Y1:", forward(P, E, S, O, Y1))

Y2 = [1, 0, 1, 0, 1, 0, 1, 0]
print("Probability for Y2:", forward(P, E, S, O, Y2))

Y3 = [0, 1, 0, 1, 0, 1, 0, 1]
print("Probability for Y3:", forward(P, E, S, O, Y3))

Y4 = [0,0,1,0,1,1,1,0]
print("Probability for Y4:", forward(P, E, S, O, Y4))

Y5 = [1, 1, 1, 1, 1, 1, 1, 1]
print("Probability for Y5:", forward(P, E, S, O, Y5))

y = [0,1]
denominator = forward(P, E, S, O, y)


Probability for Y1: 0.00390625
Probability for Y2: 0.00390625
Probability for Y3: 0.00390625
Probability for Y4: 0.00390625
Probability for Y5: 0.00390625


In [23]:
def forward_algorithm(obs_seq, pi, P, E, states, observations):
    T = len(obs_seq)
    K = len(pi)
    forward_prob = np.zeros((K, T))

    # Initialize with 'alternate' state
    forward_prob[:, 0] = np.array([0, 1, 0]) * E[:, observations.index(obs_seq[0])]

    # Recursion
    for t in range(1, T):
        for i in range(K):
            forward_prob[i, t] = sum(forward_prob[j, t-1] * P[j, i] * E[i, observations.index(obs_seq[t])] for j in range(K))

    # Termination
    prob_obs_seq = sum(forward_prob[:, T-1])
    print("Forward Probability Matrix: \n", forward_prob, "\n")
    return prob_obs_seq

In [5]:
# 1 b

import numpy as np

def forward(P, E, S, O, Y):
    pi = [0.35, 0.25, 0.4]
    mat = np.zeros([len(pi), len(Y)])
    
    for i in range(len(pi)):
        mat[i][0] = pi[i] * E[i][Y[0]]
    
    for j in range(1, len(Y)):
        for i in range(len(S)):
            total = 0
            for a in range(len(S)):
                temp = E[i, Y[j]] * P[a, i] * mat[a, j-1]
                total += temp
            mat[i, j] = total
    print(mat)
    
    prob = 0
    for i in range(len(S)):
        prob = prob + mat[i, len(Y)-1]
    
    return prob

# Define model parameters
P = np.array([[0.4,0.2,0.4],
              [0.2,0.5,0.3],
              [0.3,0.6,0.1]])
E = np.array([[0.8,0.1,0.1],
              [0.2,0.5,0.3],
              [0.4,0.2,0.4]])
S = [0, 1, 2]  # rainy cloudy sunny
O = [0, 1, 2]     # reading playing shopping

Y1 = [0,0,2,1,2]
print("Probability for [read read shop play shop]:", forward(P, E, S, O, Y1))




[[0.28       0.136      0.007864   0.00163876 0.00044851]
 [0.05       0.0354     0.023766   0.0152167  0.00285261]
 [0.16       0.0572     0.028296   0.002621   0.00219305]]
Probability for [read read shop play shop]: 0.005494170600000001


NameError: name 'Y' is not defined

In [ ]:
def calcprob(X,P,E,S,O,Y):
    pi = [0.35, 0.25, 0.4]
    mat = np.zeros([len(pi), len(Y)])
    prob[0] = pi[obs[0]] * E[X[0], obs[0]]
    for i in range(1, len(O) ):
    
    



P = np.array([[0.4,0.2,0.4],
              [0.2,0.5,0.3],
              [0.3,0.6,0.1]])
E = np.array([[0.8,0.1,0.1],
              [0.2,0.5,0.3],
              [0.4,0.2,0.4]])
S = [0, 1, 2]  # rainy cloudy sunny
O = [0, 1, 2]     # reading playing shopping

pi = np.array([0.35, 0.25, 0.4])





    